/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.dassuncao;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class UserMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 6620683817895658370L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserMessage\",\"namespace\":\"com.dassuncao\",\"fields\":[{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"password\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<UserMessage> ENCODER =
            new BinaryMessageEncoder<UserMessage>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<UserMessage> DECODER =
            new BinaryMessageDecoder<UserMessage>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<UserMessage> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<UserMessage> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<UserMessage> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<UserMessage>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this UserMessage to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a UserMessage from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a UserMessage instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static UserMessage fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    @Deprecated
    public java.lang.String email;
    @Deprecated
    public java.lang.String password;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public UserMessage() {
    }

    /**
     * All-args constructor.
     *
     * @param email    The new value for email
     * @param password The new value for password
     */
    public UserMessage(java.lang.String email, java.lang.String password) {
        this.email = email;
        this.password = password;
    }

    @com.fasterxml.jackson.annotation.JsonIgnore
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @com.fasterxml.jackson.annotation.JsonIgnore
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return email;
            case 1:
                return password;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                email = value$ != null ? value$.toString() : null;
                break;
            case 1:
                password = value$ != null ? value$.toString() : null;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'email' field.
     *
     * @return The value of the 'email' field.
     */
    public java.lang.String getEmail() {
        return email;
    }


    /**
     * Sets the value of the 'email' field.
     *
     * @param value the value to set.
     */
    public void setEmail(java.lang.String value) {
        this.email = value;
    }

    /**
     * Gets the value of the 'password' field.
     *
     * @return The value of the 'password' field.
     */
    public java.lang.String getPassword() {
        return password;
    }


    /**
     * Sets the value of the 'password' field.
     *
     * @param value the value to set.
     */
    public void setPassword(java.lang.String value) {
        this.password = value;
    }

    /**
     * Creates a new UserMessage RecordBuilder.
     *
     * @return A new UserMessage RecordBuilder
     */
    public static com.dassuncao.UserMessage.Builder newBuilder() {
        return new com.dassuncao.UserMessage.Builder();
    }

    /**
     * Creates a new UserMessage RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new UserMessage RecordBuilder
     */
    public static com.dassuncao.UserMessage.Builder newBuilder(com.dassuncao.UserMessage.Builder other) {
        if (other == null) {
            return new com.dassuncao.UserMessage.Builder();
        } else {
            return new com.dassuncao.UserMessage.Builder(other);
        }
    }

    /**
     * Creates a new UserMessage RecordBuilder by copying an existing UserMessage instance.
     *
     * @param other The existing instance to copy.
     * @return A new UserMessage RecordBuilder
     */
    public static com.dassuncao.UserMessage.Builder newBuilder(com.dassuncao.UserMessage other) {
        if (other == null) {
            return new com.dassuncao.UserMessage.Builder();
        } else {
            return new com.dassuncao.UserMessage.Builder(other);
        }
    }

    /**
     * RecordBuilder for UserMessage instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserMessage>
            implements org.apache.avro.data.RecordBuilder<UserMessage> {

        private java.lang.String email;
        private java.lang.String password;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(com.dassuncao.UserMessage.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.email)) {
                this.email = data().deepCopy(fields()[0].schema(), other.email);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.password)) {
                this.password = data().deepCopy(fields()[1].schema(), other.password);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing UserMessage instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(com.dassuncao.UserMessage other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.email)) {
                this.email = data().deepCopy(fields()[0].schema(), other.email);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.password)) {
                this.password = data().deepCopy(fields()[1].schema(), other.password);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'email' field.
         *
         * @return The value.
         */
        public java.lang.String getEmail() {
            return email;
        }


        /**
         * Sets the value of the 'email' field.
         *
         * @param value The value of 'email'.
         * @return This builder.
         */
        public com.dassuncao.UserMessage.Builder setEmail(java.lang.String value) {
            validate(fields()[0], value);
            this.email = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'email' field has been set.
         *
         * @return True if the 'email' field has been set, false otherwise.
         */
        public boolean hasEmail() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'email' field.
         *
         * @return This builder.
         */
        public com.dassuncao.UserMessage.Builder clearEmail() {
            email = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'password' field.
         *
         * @return The value.
         */
        public java.lang.String getPassword() {
            return password;
        }


        /**
         * Sets the value of the 'password' field.
         *
         * @param value The value of 'password'.
         * @return This builder.
         */
        public com.dassuncao.UserMessage.Builder setPassword(java.lang.String value) {
            validate(fields()[1], value);
            this.password = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'password' field has been set.
         *
         * @return True if the 'password' field has been set, false otherwise.
         */
        public boolean hasPassword() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'password' field.
         *
         * @return This builder.
         */
        public com.dassuncao.UserMessage.Builder clearPassword() {
            password = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public UserMessage build() {
            try {
                UserMessage record = new UserMessage();
                record.email = fieldSetFlags()[0] ? this.email : (java.lang.String) defaultValue(fields()[0]);
                record.password = fieldSetFlags()[1] ? this.password : (java.lang.String) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<UserMessage>
            WRITER$ = (org.apache.avro.io.DatumWriter<UserMessage>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<UserMessage>
            READER$ = (org.apache.avro.io.DatumReader<UserMessage>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeString(this.email);

        out.writeString(this.password);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.email = in.readString();

            this.password = in.readString();

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.email = in.readString();
                        break;

                    case 1:
                        this.password = in.readString();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










